// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: voting/aggregate_vote_count.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AggregateVoteCount struct {
	Index            string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Voter            string `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	Casted           uint64 `protobuf:"varint,3,opt,name=casted,proto3" json:"casted,omitempty"`
	PositiveReceived uint64 `protobuf:"varint,4,opt,name=positiveReceived,proto3" json:"positiveReceived,omitempty"`
	NegativeReceived uint64 `protobuf:"varint,5,opt,name=negativeReceived,proto3" json:"negativeReceived,omitempty"`
}

func (m *AggregateVoteCount) Reset()         { *m = AggregateVoteCount{} }
func (m *AggregateVoteCount) String() string { return proto.CompactTextString(m) }
func (*AggregateVoteCount) ProtoMessage()    {}
func (*AggregateVoteCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e07adad7d6f07fc, []int{0}
}
func (m *AggregateVoteCount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AggregateVoteCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AggregateVoteCount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AggregateVoteCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregateVoteCount.Merge(m, src)
}
func (m *AggregateVoteCount) XXX_Size() int {
	return m.Size()
}
func (m *AggregateVoteCount) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregateVoteCount.DiscardUnknown(m)
}

var xxx_messageInfo_AggregateVoteCount proto.InternalMessageInfo

func (m *AggregateVoteCount) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *AggregateVoteCount) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *AggregateVoteCount) GetCasted() uint64 {
	if m != nil {
		return m.Casted
	}
	return 0
}

func (m *AggregateVoteCount) GetPositiveReceived() uint64 {
	if m != nil {
		return m.PositiveReceived
	}
	return 0
}

func (m *AggregateVoteCount) GetNegativeReceived() uint64 {
	if m != nil {
		return m.NegativeReceived
	}
	return 0
}

func init() {
	proto.RegisterType((*AggregateVoteCount)(nil), "mandechain.voting.AggregateVoteCount")
}

func init() { proto.RegisterFile("voting/aggregate_vote_count.proto", fileDescriptor_5e07adad7d6f07fc) }

var fileDescriptor_5e07adad7d6f07fc = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0xcb, 0x2f, 0xc9,
	0xcc, 0x4b, 0xd7, 0x4f, 0x4c, 0x4f, 0x2f, 0x4a, 0x4d, 0x4f, 0x2c, 0x49, 0x8d, 0x2f, 0xcb, 0x2f,
	0x49, 0x8d, 0x4f, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xcc,
	0x4d, 0xcc, 0x4b, 0x49, 0x4d, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x83, 0xa8, 0x56, 0xda, 0xc0, 0xc8,
	0x25, 0xe4, 0x08, 0xd3, 0x11, 0x96, 0x5f, 0x92, 0xea, 0x0c, 0x52, 0x2f, 0x24, 0xc2, 0xc5, 0x9a,
	0x99, 0x97, 0x92, 0x5a, 0x21, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x80, 0x44, 0x41,
	0x66, 0x16, 0x49, 0x30, 0x41, 0x44, 0xc1, 0x1c, 0x21, 0x31, 0x2e, 0xb6, 0xe4, 0xc4, 0xe2, 0x92,
	0xd4, 0x14, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x28, 0x4f, 0x48, 0x8b, 0x4b, 0xa0, 0x20,
	0xbf, 0x38, 0xb3, 0x24, 0xb3, 0x2c, 0x35, 0x28, 0x35, 0x39, 0x35, 0xb3, 0x2c, 0x35, 0x45, 0x82,
	0x05, 0xac, 0x02, 0x43, 0x1c, 0xa4, 0x36, 0x0f, 0xe4, 0x04, 0x64, 0xb5, 0xac, 0x10, 0xb5, 0xe8,
	0xe2, 0x4e, 0x26, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3,
	0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0x25, 0x05, 0xf6,
	0x9f, 0x2e, 0xd8, 0x83, 0xfa, 0x15, 0xfa, 0xd0, 0x00, 0x29, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62,
	0x03, 0x07, 0x81, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xe9, 0xa1, 0xcb, 0x27, 0x01, 0x00,
	0x00,
}

func (m *AggregateVoteCount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AggregateVoteCount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AggregateVoteCount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NegativeReceived != 0 {
		i = encodeVarintAggregateVoteCount(dAtA, i, uint64(m.NegativeReceived))
		i--
		dAtA[i] = 0x28
	}
	if m.PositiveReceived != 0 {
		i = encodeVarintAggregateVoteCount(dAtA, i, uint64(m.PositiveReceived))
		i--
		dAtA[i] = 0x20
	}
	if m.Casted != 0 {
		i = encodeVarintAggregateVoteCount(dAtA, i, uint64(m.Casted))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintAggregateVoteCount(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintAggregateVoteCount(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAggregateVoteCount(dAtA []byte, offset int, v uint64) int {
	offset -= sovAggregateVoteCount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AggregateVoteCount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovAggregateVoteCount(uint64(l))
	}
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovAggregateVoteCount(uint64(l))
	}
	if m.Casted != 0 {
		n += 1 + sovAggregateVoteCount(uint64(m.Casted))
	}
	if m.PositiveReceived != 0 {
		n += 1 + sovAggregateVoteCount(uint64(m.PositiveReceived))
	}
	if m.NegativeReceived != 0 {
		n += 1 + sovAggregateVoteCount(uint64(m.NegativeReceived))
	}
	return n
}

func sovAggregateVoteCount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAggregateVoteCount(x uint64) (n int) {
	return sovAggregateVoteCount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AggregateVoteCount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAggregateVoteCount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AggregateVoteCount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AggregateVoteCount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAggregateVoteCount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAggregateVoteCount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAggregateVoteCount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAggregateVoteCount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAggregateVoteCount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAggregateVoteCount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Casted", wireType)
			}
			m.Casted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAggregateVoteCount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Casted |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositiveReceived", wireType)
			}
			m.PositiveReceived = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAggregateVoteCount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PositiveReceived |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NegativeReceived", wireType)
			}
			m.NegativeReceived = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAggregateVoteCount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NegativeReceived |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAggregateVoteCount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAggregateVoteCount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAggregateVoteCount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAggregateVoteCount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAggregateVoteCount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAggregateVoteCount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAggregateVoteCount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAggregateVoteCount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAggregateVoteCount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAggregateVoteCount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAggregateVoteCount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAggregateVoteCount = fmt.Errorf("proto: unexpected end of group")
)
