// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: voting/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetVoteBookRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetVoteBookRequest) Reset()         { *m = QueryGetVoteBookRequest{} }
func (m *QueryGetVoteBookRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVoteBookRequest) ProtoMessage()    {}
func (*QueryGetVoteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{2}
}
func (m *QueryGetVoteBookRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVoteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVoteBookRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVoteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVoteBookRequest.Merge(m, src)
}
func (m *QueryGetVoteBookRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVoteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVoteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVoteBookRequest proto.InternalMessageInfo

func (m *QueryGetVoteBookRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetVoteBookResponse struct {
	VoteBook VoteBook `protobuf:"bytes,1,opt,name=voteBook,proto3" json:"voteBook"`
}

func (m *QueryGetVoteBookResponse) Reset()         { *m = QueryGetVoteBookResponse{} }
func (m *QueryGetVoteBookResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVoteBookResponse) ProtoMessage()    {}
func (*QueryGetVoteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{3}
}
func (m *QueryGetVoteBookResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVoteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVoteBookResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVoteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVoteBookResponse.Merge(m, src)
}
func (m *QueryGetVoteBookResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVoteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVoteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVoteBookResponse proto.InternalMessageInfo

func (m *QueryGetVoteBookResponse) GetVoteBook() VoteBook {
	if m != nil {
		return m.VoteBook
	}
	return VoteBook{}
}

type QueryAllVoteBookRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVoteBookRequest) Reset()         { *m = QueryAllVoteBookRequest{} }
func (m *QueryAllVoteBookRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllVoteBookRequest) ProtoMessage()    {}
func (*QueryAllVoteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{4}
}
func (m *QueryAllVoteBookRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVoteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVoteBookRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVoteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVoteBookRequest.Merge(m, src)
}
func (m *QueryAllVoteBookRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVoteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVoteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVoteBookRequest proto.InternalMessageInfo

func (m *QueryAllVoteBookRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllVoteBookResponse struct {
	VoteBook   []VoteBook          `protobuf:"bytes,1,rep,name=voteBook,proto3" json:"voteBook"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVoteBookResponse) Reset()         { *m = QueryAllVoteBookResponse{} }
func (m *QueryAllVoteBookResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllVoteBookResponse) ProtoMessage()    {}
func (*QueryAllVoteBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{5}
}
func (m *QueryAllVoteBookResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVoteBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVoteBookResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVoteBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVoteBookResponse.Merge(m, src)
}
func (m *QueryAllVoteBookResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVoteBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVoteBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVoteBookResponse proto.InternalMessageInfo

func (m *QueryAllVoteBookResponse) GetVoteBook() []VoteBook {
	if m != nil {
		return m.VoteBook
	}
	return nil
}

func (m *QueryAllVoteBookResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAggregateVotesCastedRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetAggregateVotesCastedRequest) Reset()         { *m = QueryGetAggregateVotesCastedRequest{} }
func (m *QueryGetAggregateVotesCastedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAggregateVotesCastedRequest) ProtoMessage()    {}
func (*QueryGetAggregateVotesCastedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{6}
}
func (m *QueryGetAggregateVotesCastedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAggregateVotesCastedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAggregateVotesCastedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAggregateVotesCastedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAggregateVotesCastedRequest.Merge(m, src)
}
func (m *QueryGetAggregateVotesCastedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAggregateVotesCastedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAggregateVotesCastedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAggregateVotesCastedRequest proto.InternalMessageInfo

func (m *QueryGetAggregateVotesCastedRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetAggregateVotesCastedResponse struct {
	AggregateVotesCasted AggregateVotesCasted `protobuf:"bytes,1,opt,name=aggregateVotesCasted,proto3" json:"aggregateVotesCasted"`
}

func (m *QueryGetAggregateVotesCastedResponse) Reset()         { *m = QueryGetAggregateVotesCastedResponse{} }
func (m *QueryGetAggregateVotesCastedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAggregateVotesCastedResponse) ProtoMessage()    {}
func (*QueryGetAggregateVotesCastedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{7}
}
func (m *QueryGetAggregateVotesCastedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAggregateVotesCastedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAggregateVotesCastedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAggregateVotesCastedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAggregateVotesCastedResponse.Merge(m, src)
}
func (m *QueryGetAggregateVotesCastedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAggregateVotesCastedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAggregateVotesCastedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAggregateVotesCastedResponse proto.InternalMessageInfo

func (m *QueryGetAggregateVotesCastedResponse) GetAggregateVotesCasted() AggregateVotesCasted {
	if m != nil {
		return m.AggregateVotesCasted
	}
	return AggregateVotesCasted{}
}

type QueryAllAggregateVotesCastedRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAggregateVotesCastedRequest) Reset()         { *m = QueryAllAggregateVotesCastedRequest{} }
func (m *QueryAllAggregateVotesCastedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAggregateVotesCastedRequest) ProtoMessage()    {}
func (*QueryAllAggregateVotesCastedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{8}
}
func (m *QueryAllAggregateVotesCastedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAggregateVotesCastedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAggregateVotesCastedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAggregateVotesCastedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAggregateVotesCastedRequest.Merge(m, src)
}
func (m *QueryAllAggregateVotesCastedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAggregateVotesCastedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAggregateVotesCastedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAggregateVotesCastedRequest proto.InternalMessageInfo

func (m *QueryAllAggregateVotesCastedRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAggregateVotesCastedResponse struct {
	AggregateVotesCasted []AggregateVotesCasted `protobuf:"bytes,1,rep,name=aggregateVotesCasted,proto3" json:"aggregateVotesCasted"`
	Pagination           *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAggregateVotesCastedResponse) Reset()         { *m = QueryAllAggregateVotesCastedResponse{} }
func (m *QueryAllAggregateVotesCastedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAggregateVotesCastedResponse) ProtoMessage()    {}
func (*QueryAllAggregateVotesCastedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{9}
}
func (m *QueryAllAggregateVotesCastedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAggregateVotesCastedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAggregateVotesCastedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAggregateVotesCastedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAggregateVotesCastedResponse.Merge(m, src)
}
func (m *QueryAllAggregateVotesCastedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAggregateVotesCastedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAggregateVotesCastedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAggregateVotesCastedResponse proto.InternalMessageInfo

func (m *QueryAllAggregateVotesCastedResponse) GetAggregateVotesCasted() []AggregateVotesCasted {
	if m != nil {
		return m.AggregateVotesCasted
	}
	return nil
}

func (m *QueryAllAggregateVotesCastedResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAggregateVotesReceivedRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetAggregateVotesReceivedRequest) Reset()         { *m = QueryGetAggregateVotesReceivedRequest{} }
func (m *QueryGetAggregateVotesReceivedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAggregateVotesReceivedRequest) ProtoMessage()    {}
func (*QueryGetAggregateVotesReceivedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{10}
}
func (m *QueryGetAggregateVotesReceivedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAggregateVotesReceivedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAggregateVotesReceivedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAggregateVotesReceivedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAggregateVotesReceivedRequest.Merge(m, src)
}
func (m *QueryGetAggregateVotesReceivedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAggregateVotesReceivedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAggregateVotesReceivedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAggregateVotesReceivedRequest proto.InternalMessageInfo

func (m *QueryGetAggregateVotesReceivedRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetAggregateVotesReceivedResponse struct {
	AggregateVotesReceived AggregateVotesReceived `protobuf:"bytes,1,opt,name=aggregateVotesReceived,proto3" json:"aggregateVotesReceived"`
}

func (m *QueryGetAggregateVotesReceivedResponse) Reset() {
	*m = QueryGetAggregateVotesReceivedResponse{}
}
func (m *QueryGetAggregateVotesReceivedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAggregateVotesReceivedResponse) ProtoMessage()    {}
func (*QueryGetAggregateVotesReceivedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{11}
}
func (m *QueryGetAggregateVotesReceivedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAggregateVotesReceivedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAggregateVotesReceivedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAggregateVotesReceivedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAggregateVotesReceivedResponse.Merge(m, src)
}
func (m *QueryGetAggregateVotesReceivedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAggregateVotesReceivedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAggregateVotesReceivedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAggregateVotesReceivedResponse proto.InternalMessageInfo

func (m *QueryGetAggregateVotesReceivedResponse) GetAggregateVotesReceived() AggregateVotesReceived {
	if m != nil {
		return m.AggregateVotesReceived
	}
	return AggregateVotesReceived{}
}

type QueryAllAggregateVotesReceivedRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAggregateVotesReceivedRequest) Reset()         { *m = QueryAllAggregateVotesReceivedRequest{} }
func (m *QueryAllAggregateVotesReceivedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAggregateVotesReceivedRequest) ProtoMessage()    {}
func (*QueryAllAggregateVotesReceivedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{12}
}
func (m *QueryAllAggregateVotesReceivedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAggregateVotesReceivedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAggregateVotesReceivedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAggregateVotesReceivedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAggregateVotesReceivedRequest.Merge(m, src)
}
func (m *QueryAllAggregateVotesReceivedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAggregateVotesReceivedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAggregateVotesReceivedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAggregateVotesReceivedRequest proto.InternalMessageInfo

func (m *QueryAllAggregateVotesReceivedRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAggregateVotesReceivedResponse struct {
	AggregateVotesReceived []AggregateVotesReceived `protobuf:"bytes,1,rep,name=aggregateVotesReceived,proto3" json:"aggregateVotesReceived"`
	Pagination             *query.PageResponse      `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAggregateVotesReceivedResponse) Reset() {
	*m = QueryAllAggregateVotesReceivedResponse{}
}
func (m *QueryAllAggregateVotesReceivedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAggregateVotesReceivedResponse) ProtoMessage()    {}
func (*QueryAllAggregateVotesReceivedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08d625b0a7f5cc55, []int{13}
}
func (m *QueryAllAggregateVotesReceivedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAggregateVotesReceivedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAggregateVotesReceivedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAggregateVotesReceivedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAggregateVotesReceivedResponse.Merge(m, src)
}
func (m *QueryAllAggregateVotesReceivedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAggregateVotesReceivedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAggregateVotesReceivedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAggregateVotesReceivedResponse proto.InternalMessageInfo

func (m *QueryAllAggregateVotesReceivedResponse) GetAggregateVotesReceived() []AggregateVotesReceived {
	if m != nil {
		return m.AggregateVotesReceived
	}
	return nil
}

func (m *QueryAllAggregateVotesReceivedResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mandechain.voting.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mandechain.voting.QueryParamsResponse")
	proto.RegisterType((*QueryGetVoteBookRequest)(nil), "mandechain.voting.QueryGetVoteBookRequest")
	proto.RegisterType((*QueryGetVoteBookResponse)(nil), "mandechain.voting.QueryGetVoteBookResponse")
	proto.RegisterType((*QueryAllVoteBookRequest)(nil), "mandechain.voting.QueryAllVoteBookRequest")
	proto.RegisterType((*QueryAllVoteBookResponse)(nil), "mandechain.voting.QueryAllVoteBookResponse")
	proto.RegisterType((*QueryGetAggregateVotesCastedRequest)(nil), "mandechain.voting.QueryGetAggregateVotesCastedRequest")
	proto.RegisterType((*QueryGetAggregateVotesCastedResponse)(nil), "mandechain.voting.QueryGetAggregateVotesCastedResponse")
	proto.RegisterType((*QueryAllAggregateVotesCastedRequest)(nil), "mandechain.voting.QueryAllAggregateVotesCastedRequest")
	proto.RegisterType((*QueryAllAggregateVotesCastedResponse)(nil), "mandechain.voting.QueryAllAggregateVotesCastedResponse")
	proto.RegisterType((*QueryGetAggregateVotesReceivedRequest)(nil), "mandechain.voting.QueryGetAggregateVotesReceivedRequest")
	proto.RegisterType((*QueryGetAggregateVotesReceivedResponse)(nil), "mandechain.voting.QueryGetAggregateVotesReceivedResponse")
	proto.RegisterType((*QueryAllAggregateVotesReceivedRequest)(nil), "mandechain.voting.QueryAllAggregateVotesReceivedRequest")
	proto.RegisterType((*QueryAllAggregateVotesReceivedResponse)(nil), "mandechain.voting.QueryAllAggregateVotesReceivedResponse")
}

func init() { proto.RegisterFile("voting/query.proto", fileDescriptor_08d625b0a7f5cc55) }

var fileDescriptor_08d625b0a7f5cc55 = []byte{
	// 773 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x4f, 0x13, 0x4f,
	0x14, 0xef, 0xc0, 0x17, 0x02, 0xc3, 0xe9, 0x3b, 0x34, 0xfc, 0x58, 0xb1, 0x98, 0xc1, 0x82, 0x22,
	0xec, 0x86, 0xda, 0x00, 0xfe, 0xe0, 0x50, 0x4c, 0xe4, 0x66, 0xb0, 0x07, 0x13, 0xbd, 0x90, 0x69,
	0x99, 0xac, 0x1b, 0xb6, 0x3b, 0xa5, 0xbb, 0x34, 0x10, 0xe2, 0xc5, 0x9b, 0x07, 0x13, 0x7f, 0xfc,
	0x07, 0xfe, 0x21, 0x5e, 0x4c, 0x94, 0xc4, 0x0b, 0xd1, 0x8b, 0xf1, 0x60, 0x0c, 0xf8, 0x87, 0x98,
	0x9d, 0x7d, 0x53, 0x29, 0x9d, 0xee, 0x2e, 0xa4, 0x37, 0x98, 0x79, 0xef, 0xf3, 0x3e, 0x9f, 0xcf,
	0x7b, 0x7d, 0xb3, 0x98, 0x34, 0x45, 0xe0, 0x78, 0xb6, 0xb5, 0xbb, 0xc7, 0x1b, 0x07, 0x66, 0xbd,
	0x21, 0x02, 0x41, 0xfe, 0xaf, 0x31, 0x6f, 0x9b, 0x57, 0x9f, 0x33, 0xc7, 0x33, 0xa3, 0x6b, 0x23,
	0x6b, 0x0b, 0x5b, 0xc8, 0x5b, 0x2b, 0xfc, 0x2b, 0x0a, 0x34, 0xa6, 0x6c, 0x21, 0x6c, 0x97, 0x5b,
	0xac, 0xee, 0x58, 0xcc, 0xf3, 0x44, 0xc0, 0x02, 0x47, 0x78, 0x3e, 0xdc, 0xce, 0x57, 0x85, 0x5f,
	0x13, 0xbe, 0x55, 0x61, 0x3e, 0x8f, 0xf0, 0xad, 0xe6, 0x52, 0x85, 0x07, 0x6c, 0xc9, 0xaa, 0x33,
	0xdb, 0xf1, 0x64, 0x30, 0xc4, 0x8e, 0x02, 0x8d, 0x3a, 0x6b, 0xb0, 0x9a, 0x02, 0x18, 0x83, 0xc3,
	0xa6, 0x08, 0xf8, 0x56, 0x45, 0x88, 0x1d, 0x38, 0x9f, 0x81, 0x73, 0x66, 0xdb, 0x0d, 0x6e, 0xb3,
	0x80, 0x6f, 0x85, 0x11, 0xfe, 0x56, 0x95, 0xf9, 0x01, 0xdf, 0x86, 0xa0, 0x7c, 0x97, 0xa0, 0x06,
	0xaf, 0x72, 0xa7, 0xa9, 0xc2, 0x68, 0x16, 0x93, 0xc7, 0x21, 0xb5, 0x4d, 0x59, 0xb8, 0xcc, 0x77,
	0xf7, 0xb8, 0x1f, 0xd0, 0x47, 0x78, 0xb4, 0xed, 0xd4, 0xaf, 0x0b, 0xcf, 0xe7, 0x64, 0x05, 0x0f,
	0x46, 0x04, 0x27, 0xd0, 0x35, 0x74, 0x63, 0xa4, 0x30, 0x69, 0x76, 0x38, 0x65, 0x46, 0x29, 0xeb,
	0xff, 0x1d, 0xfd, 0x9a, 0xce, 0x94, 0x21, 0x9c, 0x5a, 0x78, 0x5c, 0xe2, 0x6d, 0xf0, 0xe0, 0x89,
	0x08, 0xf8, 0xba, 0x10, 0x3b, 0x50, 0x8a, 0x64, 0xf1, 0x80, 0xe3, 0x6d, 0xf3, 0x7d, 0x09, 0x39,
	0x5c, 0x8e, 0xfe, 0xa1, 0x4f, 0xf1, 0x44, 0x67, 0x02, 0xb0, 0x58, 0xc3, 0x43, 0x4d, 0x38, 0x03,
	0x1e, 0x57, 0x34, 0x3c, 0x54, 0x1a, 0x30, 0x69, 0xa5, 0x50, 0x06, 0x5c, 0x4a, 0xae, 0x7b, 0x9e,
	0xcb, 0x43, 0x8c, 0xff, 0x75, 0x06, 0xb0, 0x67, 0xcd, 0xa8, 0x8d, 0x66, 0xd8, 0x46, 0x33, 0x1a,
	0x13, 0x68, 0xa3, 0xb9, 0xc9, 0x6c, 0x0e, 0xb9, 0xe5, 0x33, 0x99, 0xf4, 0x03, 0x02, 0xfa, 0x6d,
	0x35, 0xb4, 0xf4, 0xfb, 0x2f, 0x48, 0x9f, 0x6c, 0xb4, 0x71, 0xec, 0x93, 0x1c, 0xe7, 0x12, 0x39,
	0x46, 0xb5, 0xdb, 0x48, 0xde, 0xc3, 0x33, 0xca, 0xe2, 0x92, 0x9a, 0x91, 0xb0, 0xaa, 0xff, 0x40,
	0x8e, 0x51, 0x7c, 0x7f, 0x5e, 0x21, 0x7c, 0x3d, 0x3e, 0x1b, 0xd4, 0x32, 0x9c, 0x65, 0x9a, 0x7b,
	0x30, 0x77, 0x4e, 0xa3, 0x5c, 0x07, 0x07, 0x2e, 0x68, 0xa1, 0x68, 0x0d, 0x84, 0x94, 0x5c, 0x37,
	0x4e, 0x48, 0xaf, 0x9a, 0xfb, 0x4d, 0x49, 0xef, 0x5a, 0x2f, 0x51, 0x7a, 0x7f, 0x8f, 0xa4, 0xf7,
	0x6e, 0x18, 0xd6, 0x70, 0x5e, 0xdf, 0xce, 0x32, 0xac, 0x8b, 0xf8, 0x71, 0x78, 0x8b, 0xf0, 0x6c,
	0x52, 0x3e, 0xb8, 0x62, 0xe3, 0x31, 0xa6, 0x8d, 0x80, 0x96, 0xdc, 0x4c, 0xf4, 0x45, 0x25, 0x80,
	0x33, 0x5d, 0xe0, 0xa8, 0x00, 0x49, 0x1d, 0x6d, 0x3a, 0x2f, 0xa9, 0x57, 0x83, 0xf1, 0x53, 0x99,
	0x10, 0x53, 0x31, 0x85, 0x09, 0xfd, 0x3d, 0x34, 0xa1, 0x67, 0x03, 0x52, 0xf8, 0x32, 0x8c, 0x07,
	0xa4, 0x38, 0x72, 0x88, 0x07, 0xa3, 0x1d, 0x4f, 0xf2, 0x1a, 0x96, 0x9d, 0x8f, 0x89, 0x31, 0x9b,
	0x14, 0x16, 0x95, 0xa3, 0xf4, 0xe5, 0xf7, 0x3f, 0xef, 0xfb, 0xa6, 0x88, 0x61, 0xc9, 0xf8, 0x45,
	0x99, 0x60, 0xb5, 0x3d, 0x8c, 0xe4, 0x1d, 0xc2, 0x43, 0x6a, 0x35, 0x92, 0xf9, 0x6e, 0xc0, 0x9d,
	0xcf, 0x8c, 0x71, 0x2b, 0x55, 0x2c, 0x30, 0x59, 0x94, 0x4c, 0xe6, 0x48, 0x5e, 0xc7, 0xa4, 0xf5,
	0x1a, 0x5b, 0x87, 0x72, 0xf8, 0x5f, 0x90, 0xd7, 0x08, 0x8f, 0x28, 0x8c, 0x92, 0xeb, 0x76, 0xe7,
	0xd5, 0xf9, 0xe4, 0x74, 0xe7, 0xa5, 0x79, 0x3a, 0x68, 0x5e, 0xf2, 0x9a, 0x26, 0x57, 0x63, 0x79,
	0x91, 0x4f, 0x08, 0x67, 0x75, 0xab, 0x84, 0x2c, 0xc7, 0x98, 0x10, 0xb3, 0x3a, 0x8d, 0x95, 0x0b,
	0xe7, 0x01, 0xe1, 0xbb, 0x92, 0x70, 0x91, 0x14, 0x74, 0x84, 0xf5, 0x9f, 0x2f, 0x2d, 0x57, 0x3f,
	0x22, 0x3c, 0xae, 0x03, 0x0f, 0x1d, 0x5e, 0x8e, 0x71, 0xed, 0x52, 0x42, 0x12, 0x76, 0x39, 0x2d,
	0x48, 0x21, 0x0b, 0x64, 0x3e, 0xbd, 0x10, 0xf2, 0x15, 0xe1, 0x31, 0xfd, 0x8f, 0x96, 0xac, 0xa6,
	0x36, 0xf4, 0xdc, 0xb2, 0x32, 0xee, 0x5c, 0x22, 0x13, 0x34, 0xdc, 0x97, 0x1a, 0x96, 0x49, 0x31,
	0x8d, 0x06, 0xf5, 0x99, 0xd8, 0x6a, 0xc7, 0x67, 0x84, 0x27, 0xf5, 0x05, 0xc2, 0x86, 0xac, 0xa6,
	0x36, 0x36, 0xb5, 0xa0, 0xc4, 0x2d, 0x4a, 0x8b, 0x52, 0x90, 0x49, 0x16, 0x2e, 0x22, 0x68, 0xbd,
	0x78, 0x74, 0x92, 0x43, 0xc7, 0x27, 0x39, 0xf4, 0xfb, 0x24, 0x87, 0xde, 0x9c, 0xe6, 0x32, 0xc7,
	0xa7, 0xb9, 0xcc, 0x8f, 0xd3, 0x5c, 0xe6, 0x99, 0x71, 0x16, 0x66, 0x5f, 0x01, 0x05, 0x07, 0x75,
	0xee, 0x57, 0x06, 0xe5, 0xe7, 0xf2, 0xed, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xda, 0xeb,
	0x93, 0x30, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a VoteBook by index.
	VoteBook(ctx context.Context, in *QueryGetVoteBookRequest, opts ...grpc.CallOption) (*QueryGetVoteBookResponse, error)
	// Queries a list of VoteBook items.
	VoteBookAll(ctx context.Context, in *QueryAllVoteBookRequest, opts ...grpc.CallOption) (*QueryAllVoteBookResponse, error)
	// Queries a AggregateVotesCasted by index.
	AggregateVotesCasted(ctx context.Context, in *QueryGetAggregateVotesCastedRequest, opts ...grpc.CallOption) (*QueryGetAggregateVotesCastedResponse, error)
	// Queries a list of AggregateVotesCasted items.
	AggregateVotesCastedAll(ctx context.Context, in *QueryAllAggregateVotesCastedRequest, opts ...grpc.CallOption) (*QueryAllAggregateVotesCastedResponse, error)
	// Queries a AggregateVotesReceived by index.
	AggregateVotesReceived(ctx context.Context, in *QueryGetAggregateVotesReceivedRequest, opts ...grpc.CallOption) (*QueryGetAggregateVotesReceivedResponse, error)
	// Queries a list of AggregateVotesReceived items.
	AggregateVotesReceivedAll(ctx context.Context, in *QueryAllAggregateVotesReceivedRequest, opts ...grpc.CallOption) (*QueryAllAggregateVotesReceivedResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mandechain.voting.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteBook(ctx context.Context, in *QueryGetVoteBookRequest, opts ...grpc.CallOption) (*QueryGetVoteBookResponse, error) {
	out := new(QueryGetVoteBookResponse)
	err := c.cc.Invoke(ctx, "/mandechain.voting.Query/VoteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteBookAll(ctx context.Context, in *QueryAllVoteBookRequest, opts ...grpc.CallOption) (*QueryAllVoteBookResponse, error) {
	out := new(QueryAllVoteBookResponse)
	err := c.cc.Invoke(ctx, "/mandechain.voting.Query/VoteBookAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AggregateVotesCasted(ctx context.Context, in *QueryGetAggregateVotesCastedRequest, opts ...grpc.CallOption) (*QueryGetAggregateVotesCastedResponse, error) {
	out := new(QueryGetAggregateVotesCastedResponse)
	err := c.cc.Invoke(ctx, "/mandechain.voting.Query/AggregateVotesCasted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AggregateVotesCastedAll(ctx context.Context, in *QueryAllAggregateVotesCastedRequest, opts ...grpc.CallOption) (*QueryAllAggregateVotesCastedResponse, error) {
	out := new(QueryAllAggregateVotesCastedResponse)
	err := c.cc.Invoke(ctx, "/mandechain.voting.Query/AggregateVotesCastedAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AggregateVotesReceived(ctx context.Context, in *QueryGetAggregateVotesReceivedRequest, opts ...grpc.CallOption) (*QueryGetAggregateVotesReceivedResponse, error) {
	out := new(QueryGetAggregateVotesReceivedResponse)
	err := c.cc.Invoke(ctx, "/mandechain.voting.Query/AggregateVotesReceived", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AggregateVotesReceivedAll(ctx context.Context, in *QueryAllAggregateVotesReceivedRequest, opts ...grpc.CallOption) (*QueryAllAggregateVotesReceivedResponse, error) {
	out := new(QueryAllAggregateVotesReceivedResponse)
	err := c.cc.Invoke(ctx, "/mandechain.voting.Query/AggregateVotesReceivedAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a VoteBook by index.
	VoteBook(context.Context, *QueryGetVoteBookRequest) (*QueryGetVoteBookResponse, error)
	// Queries a list of VoteBook items.
	VoteBookAll(context.Context, *QueryAllVoteBookRequest) (*QueryAllVoteBookResponse, error)
	// Queries a AggregateVotesCasted by index.
	AggregateVotesCasted(context.Context, *QueryGetAggregateVotesCastedRequest) (*QueryGetAggregateVotesCastedResponse, error)
	// Queries a list of AggregateVotesCasted items.
	AggregateVotesCastedAll(context.Context, *QueryAllAggregateVotesCastedRequest) (*QueryAllAggregateVotesCastedResponse, error)
	// Queries a AggregateVotesReceived by index.
	AggregateVotesReceived(context.Context, *QueryGetAggregateVotesReceivedRequest) (*QueryGetAggregateVotesReceivedResponse, error)
	// Queries a list of AggregateVotesReceived items.
	AggregateVotesReceivedAll(context.Context, *QueryAllAggregateVotesReceivedRequest) (*QueryAllAggregateVotesReceivedResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) VoteBook(ctx context.Context, req *QueryGetVoteBookRequest) (*QueryGetVoteBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteBook not implemented")
}
func (*UnimplementedQueryServer) VoteBookAll(ctx context.Context, req *QueryAllVoteBookRequest) (*QueryAllVoteBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteBookAll not implemented")
}
func (*UnimplementedQueryServer) AggregateVotesCasted(ctx context.Context, req *QueryGetAggregateVotesCastedRequest) (*QueryGetAggregateVotesCastedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateVotesCasted not implemented")
}
func (*UnimplementedQueryServer) AggregateVotesCastedAll(ctx context.Context, req *QueryAllAggregateVotesCastedRequest) (*QueryAllAggregateVotesCastedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateVotesCastedAll not implemented")
}
func (*UnimplementedQueryServer) AggregateVotesReceived(ctx context.Context, req *QueryGetAggregateVotesReceivedRequest) (*QueryGetAggregateVotesReceivedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateVotesReceived not implemented")
}
func (*UnimplementedQueryServer) AggregateVotesReceivedAll(ctx context.Context, req *QueryAllAggregateVotesReceivedRequest) (*QueryAllAggregateVotesReceivedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateVotesReceivedAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.voting.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVoteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.voting.Query/VoteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteBook(ctx, req.(*QueryGetVoteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteBookAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllVoteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteBookAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.voting.Query/VoteBookAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteBookAll(ctx, req.(*QueryAllVoteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AggregateVotesCasted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAggregateVotesCastedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AggregateVotesCasted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.voting.Query/AggregateVotesCasted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AggregateVotesCasted(ctx, req.(*QueryGetAggregateVotesCastedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AggregateVotesCastedAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAggregateVotesCastedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AggregateVotesCastedAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.voting.Query/AggregateVotesCastedAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AggregateVotesCastedAll(ctx, req.(*QueryAllAggregateVotesCastedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AggregateVotesReceived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAggregateVotesReceivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AggregateVotesReceived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.voting.Query/AggregateVotesReceived",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AggregateVotesReceived(ctx, req.(*QueryGetAggregateVotesReceivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AggregateVotesReceivedAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAggregateVotesReceivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AggregateVotesReceivedAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.voting.Query/AggregateVotesReceivedAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AggregateVotesReceivedAll(ctx, req.(*QueryAllAggregateVotesReceivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mandechain.voting.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "VoteBook",
			Handler:    _Query_VoteBook_Handler,
		},
		{
			MethodName: "VoteBookAll",
			Handler:    _Query_VoteBookAll_Handler,
		},
		{
			MethodName: "AggregateVotesCasted",
			Handler:    _Query_AggregateVotesCasted_Handler,
		},
		{
			MethodName: "AggregateVotesCastedAll",
			Handler:    _Query_AggregateVotesCastedAll_Handler,
		},
		{
			MethodName: "AggregateVotesReceived",
			Handler:    _Query_AggregateVotesReceived_Handler,
		},
		{
			MethodName: "AggregateVotesReceivedAll",
			Handler:    _Query_AggregateVotesReceivedAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voting/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetVoteBookRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVoteBookRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVoteBookRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVoteBookResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVoteBookResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVoteBookResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.VoteBook.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllVoteBookRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVoteBookRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVoteBookRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllVoteBookResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVoteBookResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVoteBookResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.VoteBook) > 0 {
		for iNdEx := len(m.VoteBook) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VoteBook[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAggregateVotesCastedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAggregateVotesCastedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAggregateVotesCastedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAggregateVotesCastedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAggregateVotesCastedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAggregateVotesCastedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AggregateVotesCasted.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAggregateVotesCastedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAggregateVotesCastedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAggregateVotesCastedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAggregateVotesCastedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAggregateVotesCastedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAggregateVotesCastedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AggregateVotesCasted) > 0 {
		for iNdEx := len(m.AggregateVotesCasted) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AggregateVotesCasted[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAggregateVotesReceivedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAggregateVotesReceivedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAggregateVotesReceivedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAggregateVotesReceivedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAggregateVotesReceivedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAggregateVotesReceivedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AggregateVotesReceived.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAggregateVotesReceivedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAggregateVotesReceivedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAggregateVotesReceivedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAggregateVotesReceivedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAggregateVotesReceivedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAggregateVotesReceivedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AggregateVotesReceived) > 0 {
		for iNdEx := len(m.AggregateVotesReceived) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AggregateVotesReceived[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetVoteBookRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVoteBookResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VoteBook.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllVoteBookRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllVoteBookResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.VoteBook) > 0 {
		for _, e := range m.VoteBook {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAggregateVotesCastedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAggregateVotesCastedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AggregateVotesCasted.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAggregateVotesCastedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAggregateVotesCastedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AggregateVotesCasted) > 0 {
		for _, e := range m.AggregateVotesCasted {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAggregateVotesReceivedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAggregateVotesReceivedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AggregateVotesReceived.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAggregateVotesReceivedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAggregateVotesReceivedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AggregateVotesReceived) > 0 {
		for _, e := range m.AggregateVotesReceived {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVoteBookRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVoteBookRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVoteBookRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVoteBookResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVoteBookResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVoteBookResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteBook", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteBook.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVoteBookRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVoteBookRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVoteBookRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVoteBookResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVoteBookResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVoteBookResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteBook", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteBook = append(m.VoteBook, VoteBook{})
			if err := m.VoteBook[len(m.VoteBook)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAggregateVotesCastedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAggregateVotesCastedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAggregateVotesCastedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAggregateVotesCastedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAggregateVotesCastedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAggregateVotesCastedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregateVotesCasted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AggregateVotesCasted.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAggregateVotesCastedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAggregateVotesCastedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAggregateVotesCastedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAggregateVotesCastedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAggregateVotesCastedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAggregateVotesCastedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregateVotesCasted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AggregateVotesCasted = append(m.AggregateVotesCasted, AggregateVotesCasted{})
			if err := m.AggregateVotesCasted[len(m.AggregateVotesCasted)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAggregateVotesReceivedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAggregateVotesReceivedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAggregateVotesReceivedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAggregateVotesReceivedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAggregateVotesReceivedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAggregateVotesReceivedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregateVotesReceived", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AggregateVotesReceived.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAggregateVotesReceivedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAggregateVotesReceivedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAggregateVotesReceivedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAggregateVotesReceivedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAggregateVotesReceivedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAggregateVotesReceivedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregateVotesReceived", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AggregateVotesReceived = append(m.AggregateVotesReceived, AggregateVotesReceived{})
			if err := m.AggregateVotesReceived[len(m.AggregateVotesReceived)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
