
FROM node:16.13.2-alpine
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /usr/app
RUN git clone https://github.com/karthiktsaliki/faucet.git

WORKDIR /usr/app/faucet
RUN npm install
