version: "3.7"

services:

  test-node-1:
    image: mandechain/mande_chain:latest
    restart: always
    stdin_open: true
    tty: true
    container_name: test-node-1
    entrypoint: /usr/local/bin/run_genesis_node.sh
    environment:
      - CONFIG_TOML=/root/.mande-chain/config/config.toml
      - APP_TOML=/root/.mande-chain/config/app.toml
      - MONIKER=test-node-1
      - VALIDATOR_NAME=validator_main

  test-node-2:
    image: mandechain/mande_chain:latest
    restart: always
    stdin_open: true
    tty: true
    container_name: test-node-2
#    entrypoint: /usr/local/bin/run_validator_node.sh
    environment:
      - CONFIG_TOML=/root/.mande-chain/config/config.toml
      - APP_TOML=/root/.mande-chain/config/app.toml
      - MONIKER=test-node-2
      - VALIDATOR_NAME=validator_2
    depends_on:
      - test-node-1

  frontend:
    build: ./vue
    command: npm run dev -- --host
    restart: always
    volumes:
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - test-node-1
      - test-node-2

  redis:
    image: redis:latest
    restart: always
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]

  faucet:
    build:
      context: .
      dockerfile: Dockerfile_faucet
    command: npm start
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - redis
