// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oracle/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryNetworkConstantRequest struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryNetworkConstantRequest) Reset()         { *m = QueryNetworkConstantRequest{} }
func (m *QueryNetworkConstantRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNetworkConstantRequest) ProtoMessage()    {}
func (*QueryNetworkConstantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{2}
}
func (m *QueryNetworkConstantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNetworkConstantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNetworkConstantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNetworkConstantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNetworkConstantRequest.Merge(m, src)
}
func (m *QueryNetworkConstantRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNetworkConstantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNetworkConstantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNetworkConstantRequest proto.InternalMessageInfo

func (m *QueryNetworkConstantRequest) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

type QueryNetworkConstantResponse struct {
	Result *NetworkConstantResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *QueryNetworkConstantResponse) Reset()         { *m = QueryNetworkConstantResponse{} }
func (m *QueryNetworkConstantResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNetworkConstantResponse) ProtoMessage()    {}
func (*QueryNetworkConstantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{3}
}
func (m *QueryNetworkConstantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNetworkConstantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNetworkConstantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNetworkConstantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNetworkConstantResponse.Merge(m, src)
}
func (m *QueryNetworkConstantResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNetworkConstantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNetworkConstantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNetworkConstantResponse proto.InternalMessageInfo

func (m *QueryNetworkConstantResponse) GetResult() *NetworkConstantResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryLastNetworkConstantIdRequest struct {
}

func (m *QueryLastNetworkConstantIdRequest) Reset()         { *m = QueryLastNetworkConstantIdRequest{} }
func (m *QueryLastNetworkConstantIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLastNetworkConstantIdRequest) ProtoMessage()    {}
func (*QueryLastNetworkConstantIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{4}
}
func (m *QueryLastNetworkConstantIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastNetworkConstantIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastNetworkConstantIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastNetworkConstantIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastNetworkConstantIdRequest.Merge(m, src)
}
func (m *QueryLastNetworkConstantIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastNetworkConstantIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastNetworkConstantIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastNetworkConstantIdRequest proto.InternalMessageInfo

type QueryLastNetworkConstantIdResponse struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryLastNetworkConstantIdResponse) Reset()         { *m = QueryLastNetworkConstantIdResponse{} }
func (m *QueryLastNetworkConstantIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLastNetworkConstantIdResponse) ProtoMessage()    {}
func (*QueryLastNetworkConstantIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{5}
}
func (m *QueryLastNetworkConstantIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastNetworkConstantIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastNetworkConstantIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastNetworkConstantIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastNetworkConstantIdResponse.Merge(m, src)
}
func (m *QueryLastNetworkConstantIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastNetworkConstantIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastNetworkConstantIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastNetworkConstantIdResponse proto.InternalMessageInfo

func (m *QueryLastNetworkConstantIdResponse) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mandechain.oracle.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mandechain.oracle.QueryParamsResponse")
	proto.RegisterType((*QueryNetworkConstantRequest)(nil), "mandechain.oracle.QueryNetworkConstantRequest")
	proto.RegisterType((*QueryNetworkConstantResponse)(nil), "mandechain.oracle.QueryNetworkConstantResponse")
	proto.RegisterType((*QueryLastNetworkConstantIdRequest)(nil), "mandechain.oracle.QueryLastNetworkConstantIdRequest")
	proto.RegisterType((*QueryLastNetworkConstantIdResponse)(nil), "mandechain.oracle.QueryLastNetworkConstantIdResponse")
}

func init() { proto.RegisterFile("oracle/query.proto", fileDescriptor_562b782cb9ac197e) }

var fileDescriptor_562b782cb9ac197e = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x13, 0xaf, 0x06, 0x1c, 0x57, 0xce, 0xbd, 0x82, 0xc6, 0xde, 0xa8, 0x23, 0xca, 0x45,
	0xb9, 0x19, 0x6e, 0x5b, 0x29, 0x82, 0xa0, 0xb4, 0xab, 0x82, 0x14, 0xcd, 0xd2, 0x4d, 0x9c, 0x26,
	0x43, 0x0c, 0xa6, 0x33, 0x69, 0x66, 0xa2, 0x96, 0xe2, 0xc6, 0x27, 0x10, 0x7c, 0x1a, 0xdf, 0xa0,
	0xcb, 0x82, 0x1b, 0x57, 0x22, 0xad, 0x8f, 0xe1, 0x42, 0x3a, 0x33, 0xa5, 0xd6, 0xa4, 0x55, 0x77,
	0x61, 0xce, 0xff, 0xff, 0xf3, 0x9d, 0x73, 0x26, 0x00, 0xf2, 0x82, 0x44, 0x19, 0xc5, 0xe3, 0x92,
	0x16, 0x13, 0x3f, 0x2f, 0xb8, 0xe4, 0xf0, 0xf2, 0x88, 0xb0, 0x98, 0x46, 0xaf, 0x48, 0xca, 0x7c,
	0x5d, 0x76, 0x8f, 0x12, 0x9e, 0x70, 0x55, 0xc5, 0xab, 0x2f, 0x2d, 0x74, 0x1b, 0x09, 0xe7, 0x49,
	0x46, 0x31, 0xc9, 0x53, 0x4c, 0x18, 0xe3, 0x92, 0xc8, 0x94, 0x33, 0x61, 0xaa, 0xf7, 0x22, 0x2e,
	0x46, 0x5c, 0xe0, 0x21, 0x11, 0x26, 0x1f, 0xbf, 0x39, 0x1b, 0x52, 0x49, 0xce, 0x70, 0x4e, 0x92,
	0x94, 0x29, 0xb1, 0xd1, 0x1e, 0x1a, 0x8c, 0x9c, 0x14, 0x64, 0xb4, 0x0e, 0x38, 0x36, 0x87, 0x8c,
	0xca, 0xb7, 0xbc, 0x78, 0x1d, 0x46, 0x9c, 0x09, 0x49, 0x98, 0xd4, 0x65, 0x74, 0x04, 0xe0, 0xf3,
	0x55, 0xea, 0x33, 0xe5, 0x09, 0xe8, 0xb8, 0xa4, 0x42, 0xa2, 0x01, 0x38, 0xdc, 0x3a, 0x15, 0x39,
	0x67, 0x82, 0xc2, 0x0e, 0x70, 0x74, 0xf6, 0x55, 0xfb, 0xa6, 0x7d, 0x72, 0xa9, 0x79, 0xcd, 0xaf,
	0x34, 0xe9, 0x6b, 0x4b, 0xf7, 0xfc, 0xec, 0xdb, 0x0d, 0x2b, 0x30, 0x72, 0xf4, 0x08, 0x5c, 0x57,
	0x79, 0x03, 0x0d, 0xd1, 0x33, 0x0c, 0xe6, 0x3a, 0x78, 0x0c, 0x40, 0xa1, 0x3f, 0xc3, 0x34, 0x56,
	0xd9, 0x07, 0xc1, 0x45, 0x73, 0xd2, 0x8f, 0xd1, 0x4b, 0xd0, 0xa8, 0x77, 0x1b, 0xac, 0x27, 0xc0,
	0x29, 0xa8, 0x28, 0x33, 0x69, 0xb0, 0x4e, 0x6a, 0xb0, 0xaa, 0xde, 0x32, 0x93, 0x81, 0xf1, 0xa1,
	0xdb, 0xe0, 0x96, 0xba, 0xe1, 0x29, 0x11, 0xf2, 0x0f, 0x65, 0x3f, 0x5e, 0x0f, 0xa5, 0x07, 0xd0,
	0x3e, 0x91, 0x81, 0xd9, 0xdf, 0x4b, 0xf3, 0xe7, 0x01, 0xb8, 0xa0, 0x52, 0xe0, 0x14, 0x38, 0x7a,
	0x56, 0xf0, 0x4e, 0x0d, 0x6f, 0x75, 0x29, 0xee, 0xdd, 0xbf, 0xc9, 0x34, 0x01, 0x42, 0x1f, 0xbe,
	0xfc, 0xf8, 0x74, 0xae, 0x01, 0x5d, 0xac, 0xf4, 0xa7, 0xca, 0x80, 0xb7, 0xde, 0x06, 0xfc, 0x6c,
	0x83, 0x2b, 0xb5, 0x23, 0x81, 0xfe, 0xae, 0x5b, 0xea, 0x77, 0xe7, 0xe2, 0x7f, 0xd6, 0x1b, 0xbc,
	0xc7, 0x0a, 0xef, 0x21, 0xec, 0xe0, 0x8d, 0x11, 0xef, 0x78, 0xa4, 0xa1, 0xde, 0x0f, 0x9e, 0x6e,
	0x46, 0xfa, 0x5e, 0xb1, 0xd7, 0xee, 0x00, 0xb6, 0x77, 0xb1, 0xec, 0xdb, 0xab, 0xfb, 0xe0, 0x3f,
	0x5d, 0xa6, 0x8f, 0x96, 0xea, 0xe3, 0x14, 0xde, 0xaf, 0xe9, 0x23, 0x23, 0x42, 0x86, 0x95, 0x66,
	0xd2, 0xb8, 0xdb, 0x9e, 0x2d, 0x3c, 0x7b, 0xbe, 0xf0, 0xec, 0xef, 0x0b, 0xcf, 0xfe, 0xb8, 0xf4,
	0xac, 0xf9, 0xd2, 0xb3, 0xbe, 0x2e, 0x3d, 0xeb, 0x85, 0xfb, 0xfb, 0xb2, 0xde, 0xad, 0x83, 0xe4,
	0x24, 0xa7, 0x62, 0xe8, 0xa8, 0x7f, 0xb5, 0xf5, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x33, 0xf0,
	0xe1, 0x68, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// NetworkConstantResult defines a rpc handler method for MsgNetworkConstantData.
	NetworkConstantResult(ctx context.Context, in *QueryNetworkConstantRequest, opts ...grpc.CallOption) (*QueryNetworkConstantResponse, error)
	// LastNetworkConstantId query the last NetworkConstant result id
	LastNetworkConstantId(ctx context.Context, in *QueryLastNetworkConstantIdRequest, opts ...grpc.CallOption) (*QueryLastNetworkConstantIdResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mandechain.oracle.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NetworkConstantResult(ctx context.Context, in *QueryNetworkConstantRequest, opts ...grpc.CallOption) (*QueryNetworkConstantResponse, error) {
	out := new(QueryNetworkConstantResponse)
	err := c.cc.Invoke(ctx, "/mandechain.oracle.Query/NetworkConstantResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastNetworkConstantId(ctx context.Context, in *QueryLastNetworkConstantIdRequest, opts ...grpc.CallOption) (*QueryLastNetworkConstantIdResponse, error) {
	out := new(QueryLastNetworkConstantIdResponse)
	err := c.cc.Invoke(ctx, "/mandechain.oracle.Query/LastNetworkConstantId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// NetworkConstantResult defines a rpc handler method for MsgNetworkConstantData.
	NetworkConstantResult(context.Context, *QueryNetworkConstantRequest) (*QueryNetworkConstantResponse, error)
	// LastNetworkConstantId query the last NetworkConstant result id
	LastNetworkConstantId(context.Context, *QueryLastNetworkConstantIdRequest) (*QueryLastNetworkConstantIdResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) NetworkConstantResult(ctx context.Context, req *QueryNetworkConstantRequest) (*QueryNetworkConstantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkConstantResult not implemented")
}
func (*UnimplementedQueryServer) LastNetworkConstantId(ctx context.Context, req *QueryLastNetworkConstantIdRequest) (*QueryLastNetworkConstantIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastNetworkConstantId not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.oracle.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NetworkConstantResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNetworkConstantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NetworkConstantResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.oracle.Query/NetworkConstantResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NetworkConstantResult(ctx, req.(*QueryNetworkConstantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastNetworkConstantId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLastNetworkConstantIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastNetworkConstantId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mandechain.oracle.Query/LastNetworkConstantId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastNetworkConstantId(ctx, req.(*QueryLastNetworkConstantIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mandechain.oracle.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "NetworkConstantResult",
			Handler:    _Query_NetworkConstantResult_Handler,
		},
		{
			MethodName: "LastNetworkConstantId",
			Handler:    _Query_LastNetworkConstantId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryNetworkConstantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNetworkConstantRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNetworkConstantRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryNetworkConstantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNetworkConstantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNetworkConstantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLastNetworkConstantIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastNetworkConstantIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastNetworkConstantIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLastNetworkConstantIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastNetworkConstantIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastNetworkConstantIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryNetworkConstantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func (m *QueryNetworkConstantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLastNetworkConstantIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLastNetworkConstantIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNetworkConstantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNetworkConstantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNetworkConstantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNetworkConstantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNetworkConstantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNetworkConstantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &NetworkConstantResult{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastNetworkConstantIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastNetworkConstantIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastNetworkConstantIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastNetworkConstantIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastNetworkConstantIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastNetworkConstantIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
